"""Add is_admin column to user table

Revision ID: 0486ad53c800
Revises: d127ebd7ac77
Create Date: 2026-01-16 23:09:54.099700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0486ad53c800'
down_revision = 'd127ebd7ac77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
